services:
  - type: web
    name: ares-proxy
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FIREBASE_DB_SECRET
        sync: false
      - key: PROXY_API_KEY
        sync: false
